job-android:

  stage: build
  tags: [ "docker-android" ]

  image: gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-android:r16b
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CMAKE_GENERATOR: Ninja

  script:
    - which sdkmanager
    - yes | sdkmanager "build-tools;27.0.3"
    - ./prepare.py
    - make
    - cp bin/outputs/apk/debug/linphone-android-obiane-debug.apk android-obiane.apk
    - make unsigned
    - cp bin/outputs/apk/packaged/linphone-android-obiane-packaged-unsigned.apk android-obiane-unsigned.apk

  artifacts:
    paths:
      - android-obiane-unsigned.apk
      - android-obiane.apk
    when: always
    expire_in: 1 week


stages:
 - build
